apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../helm-repositories/metallb.yaml
  - ../../../helm-repositories/ngrok.yaml
  - ../../../helm-repositories/prometheus-community.yaml
