apiVersion: v1
kind: Secret
metadata:
  name: cluster-secret-vars
  namespace: flux-system
  labels:
    version: v2
type: Opaque
data:
  ngrok_api_key: ENC[AES256_GCM,data:IuIJh5OrH76twRHFl0c7hXYmlrOGC1nzRGSYkusSVMyK2Y6FulTyo/Hi2vqf/f2DxzrNEitY/O4oUuM0euv61CUElyU=,iv:+84c/sjMoGSXvvzPBtvoLyocpU6+dtiu5aR7rJ+uV30=,tag:ppIef1d3I/x2pxla2g35Ww==,type:str]
  ngrok_authtoken: ENC[AES256_GCM,data:mfKKHMeGuInCy39oXrHMb86Sshcrq4oxpsGPOUq/ax5Za+XMFmwoewo/JkG/w3Arq6xwZD0vyYOc6E+dQnhP8mLhMQg=,iv:9kMU+cJH43qZPWBq1fdnNGYtkL8J8FxIy+yZY4yqEHc=,tag:zSLqzAVCfw2Qtw1CO5KZxg==,type:str]
  ngrok_domain: ENC[AES256_GCM,data:oaVVx8rZ/Yv65pxXRQ3PH3NWSwcX4mRSrcFYxQI53FKvUR38J1w6tObFJq73bFeXSmI24B2wEZ0rUSpSHHl0og==,iv:ovLyxq53EcBjhjeG5UKezt1SQbLgamUuLVgd5anHJJM=,tag:sJX08e2kvsrG6+v2fiU1kQ==,type:str]
sops:
  age:
    - recipient: age1fe4qsmk5psclxsct8fmq5lenama3zt7vt35arsxqslxlskcp9pjsup39qj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bnU5UmZrL29Cdi8zTXNo
        RnVKU1p5YnhwU09MTjhmeDJHQWtSenJISjJjCkZFTUgwejFzQ1l5Vm5tdzk0YW8v
        STZJQm03RTh3eW0wdTY0SUNhNVFDaUUKLS0tIGpVU2hXaTcxZndpQ2svVFhPV1FC
        cXBVL2crY21ROXlyVnNxdEFEdmh0SHMKzghpl2o+bUizLDWjvhGQEAoKUqqIERGk
        AILijn+9XVjmrQnNIGGBmjf4TT4Sayoa6aczRhMN4hT2aeXkCZwSZQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rp8qrv3nek4se3a23hw4kzy0k9yh4spjgkcx6rj8wg0ddd3yl92qyqlujg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZb2U1UkFTV2FEWjZuck5G
        eHlBWFVNeVRWeTFvVjhYWUNETEtjNzdnMUM0Cnd5bmtzMW1vRzNPQjBuWkxJNVoy
        cTRPRjI4aWZzMytnL09LRFJOdzh2bnMKLS0tIC9EZTI3SHJaMnhQZ3dWMHRUNXdU
        eERlMUZzaVRxcExkM3g2UWlSNjF0TTgKpG5rrJ+7WHRcMZbJA9NHFi89EyQMBVds
        nGhwmhabhHGPOsoVS+r5S8MhAOCj3qBKxmrWSYoKX5O7/oJtBXXF6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T21:43:27Z"
  mac: ENC[AES256_GCM,data:UOww3xoLPI9xqUFHv7uEcL0xOTXoMQHhpCDYdQJtVEmw2hRxZFNbVHrOI4bg7b4Wywd5Yu1KFdLG4aTxPWeTobrGqgcoVwym+uJi/4c7l4Zr8b+SZIj4kxR2mFYEkPkj76Z4qN3UQviJ/ghyERYglXA7YaEqX0bH2p2ggsswd+8=,iv:Gok9TIQ5l1uB0aw5FvwgwB/sRpnsV5xfagOnyYr3bzM=,tag:9PoEIZDjH6rNvQ8pwqHFrg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
