apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - kustomize/namespace.yaml
resources:
  - cluster-role-binding.yaml
  - helm-release.yaml
  - secret.yaml
  - service-account.yaml
