apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system.yaml
  - kube-prometheus-stack.yaml
  - metallb-ip-pools.yaml
  - metallb.yaml
  - ngrok-operator.yaml
  # - ngrok.yaml
